### ISSUE TITLE
ru lang

### ISSUE THREAD

**Issue by juxta73** [LeviticusMB/bestest_timer#3]
Hello, thx for great plugin!

ru lang here

  bestest_timer:
    activity: "Статус"
    close: "Закрыть"
    comment: "Комментарий"
    commit: "Записать"
    discard: "Отменить"
    logging_since: "%{descr} с %{time}"
    need_rest_api: "Пожалуйста, проверьте, что опция 'Включить веб-сервис REST'' активирована — администрирование/Настройки/API."
    no_permission: "У вас нет разрешений для учета времени в проекте %{project}."
    nothing_inferred: "Нужно выбрать задачу или проект, чтобы запустить учет времени"
    notification_title: "Учтено %{hours} ч. для %{descr}"
    plugin_name: "Лучший учет времени для Redmine"
    recording: "(Ведется учет времени)"
    start: "Запустить учет времени"
    state_descr_issue: "%{project}, задача #%{issue}"
    state_descr: "%{project}"
    submit_failed: "Не удалось учесть время: %{error}"

and i have style glitch (black line) in safari 
<img width="434" alt="2017-03-17 17 17 48" src="https://cloud.githubusercontent.com/assets/25210160/24044917/b00d6f26-0b36-11e7-909e-75599d72e654.png">

**Comment by LeviticusMB** [comment]
Thx!

In the 1.1 branch, I've added a "Status" language key too. What's that in Russian?
