### ISSUE TITLE
DE language

### ISSUE THREAD

**Issue by Winslow-AT** [LeviticusMB/bestest_timer#7]
Hi,

thanks for the plugin, german translation:

bestest_timer:
    plugin_name: "Bestest Punch Clock for Redmine"

    start: "Uhr starten"
    recording: "(Aufzeichnung)"

    details: "Details"
    time: "Zeit:"
    project: "Projekt:"
    issue: "Ticket:"

    activity: "Aktivit├ñt"

    comment: "Kommentar"

    commit: "Buchen"
    discard: "Verwerfen"
    close: "Beenden"

    logging_since: "Buchung auf %{descr} seit %{time}"
    notification_title: "%{hours} Stunden zu %{descr} gebucht"
    state_descr_issue: "%{project}, Ticket #%{issue}"
    state_descr: "%{project}"

    need_rest_api: "Bitte pr├âfen Sie ob 'REST-Schnittstelle aktivieren' in Redmine unter Administration/Konfiguration/API aktiviert ist."
    no_permission: "Sie haben keine Berechtigungen Zeit auf %{project} zu buchen."
    nothing_inferred: "Weder das Projekt noch das Ticket konnte von der aktuellen Seite abgeleitet werden."
    submit_failed: "Fehler beim Buchen zu Redmine: %{error}"

**Comment by LeviticusMB** [comment]
Thanks! 

Could you please also translate the plugin name? (“Bestest” is “better than the best” in a grammatically incorrect way.)

Skickat från min iPhone

**Comment by Winslow-AT** [comment]
If you want the same grammatically incorrect way in german it would be 

"Die besteste Stempeluhr für Redmine"

correct way:

"Die beste Stempeluhr für Redmine"

**Comment by LeviticusMB** [comment]
There were some encoding errors in your message. Please check that I got the umlauts right in the `v1.2` branch.
