### ISSUE TITLE
Daylight savings

### ISSUE THREAD

**Issue by ianmorpht** [LeviticusMB/bestest_timer#9]
The majority of Australia kicked over into daylight savings last weekend. Bestest Timer is reflecting the pre-daylight savings time still. Are you able to confirm where the time is sourced when punching in?

**Comment by LeviticusMB** [comment]
Is this still a problem? I tried to reproduce and found that at least my Firefox DE didn't pick up TZ changes immediately, but did return to proper behavior if the tab was reloaded.

**Comment by ianmorpht** [comment]
Hi there.

It was still a problem until I updated Chrome 61.x to Chrome 62.x about half an hour ago. Despite having auto update turned on for Chrome, it did not update until I manually intervened. (macOS Sierra 10.12.6, Chrome 61.x, MacBook Pro 2015)

The punch clock timer is now reflecting system time.

Many thanks for your response.
